//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.TrainingModule.Persistence.Contexts;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.EmployeeTraining;
using QuickCode.Demomusti.TrainingModule.Application.Mappings;
using QuickCode.Demomusti.TrainingModule.Persistence.Sql;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Persistence.Repositories
{
    public partial class EmployeeTrainingRepository : BaseRepository, IEmployeeTrainingRepository
    {
        public async Task<RepoResponse<List<GetByEmployeeResponseDto>>> GetByEmployeeAsync(int employeeTrainingEmployeeId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByEmployee", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByEmployeeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EmployeeTraining.Query.GetByEmployee);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_EMPLOYEE_TRAINING_EMPLOYEE_ID = employeeTrainingEmployeeId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByEmployeeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EmployeeTraining");
                }
            });
        }

        public async Task<RepoResponse<List<GetByTrainingResponseDto>>> GetByTrainingAsync(int employeeTrainingTrainingId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByTraining", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByTrainingResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.EmployeeTraining.Query.GetByTraining);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_EMPLOYEE_TRAINING_TRAINING_ID = employeeTrainingTrainingId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByTrainingResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in EmployeeTraining");
                }
            });
        }

        public async Task<RepoResponse<List<GetTrainingFeedbacksForEmployeeTrainingsResponseDto>>> GetTrainingFeedbacksForEmployeeTrainingsAsync(int employeeTrainingsId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingFeedbacksForEmployeeTrainings", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EmployeeTraining.Query.GetTrainingFeedbacksForEmployeeTrainings);
                var parameters = new
                {
                    employeeTrainingsId = employeeTrainingsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTrainingFeedbacksForEmployeeTrainingsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in EmployeeTraining");
            });
        }

        public async Task<RepoResponse<GetTrainingFeedbacksForEmployeeTrainingsResponseDto>> GetTrainingFeedbacksForEmployeeTrainingsDetailsAsync(int employeeTrainingsId, int trainingFeedbacksId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingFeedbacksForEmployeeTrainingsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.EmployeeTraining.Query.GetTrainingFeedbacksForEmployeeTrainingsDetails);
                var parameters = new
                {
                    employeeTrainingsId = employeeTrainingsId,
                    trainingFeedbacksId = trainingFeedbacksId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetTrainingFeedbacksForEmployeeTrainingsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in EmployeeTraining");
            });
        }
    }
}