SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL], [DEPARTMENT] 
FROM [INTERVIEWERS] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_INTERVIEWER_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 