SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL], [DEPARTMENT] 
FROM [INTERVIEWERS] 
WHERE [IsDeleted] = 0 
	AND [FIRST_NAME] LIKE '%' + @PRM_INTERVIEWER_FIRST_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 