//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.CandidateTrackingModule.Persistence.Contexts;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.Candidate;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Mappings;
using QuickCode.Demomusti.CandidateTrackingModule.Persistence.Sql;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Persistence.Repositories
{
    public partial class CandidateRepository : BaseRepository, ICandidateRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int candidateId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Candidate", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Candidate.Command.UpdateStatus);
                var parameters = new
                {
                    CANDIDATE_APPLICATION_STATUS = updateRequest.CandidateApplicationStatus,
                    PRM_CANDIDATE_ID = candidateId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> ActivateAsync(int candidateId, ActivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Candidate", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Candidate.Command.Activate);
                var parameters = new
                {
                    PRM_CANDIDATE_ID = candidateId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int candidateId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Candidate", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Candidate.Command.Deactivate);
                var parameters = new
                {
                    PRM_CANDIDATE_ID = candidateId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}