SELECT [ID], [COURSE_NAME], [TRAINING_TYPE], [START_DATE], [END_DATE] 
FROM [TRAININGS] 
WHERE [IsDeleted] = 0 
	AND [STATUS] = @PRM_TRAINING_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 