SELECT [ID], [COURSE_NAME], [START_DATE], [END_DATE] 
FROM [TRAININGS] 
WHERE [IsDeleted] = 0 
	AND [TRAINING_TYPE] = @PRM_TRAINING_TRAINING_TYPE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 