//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.ApiMethodDefinition;
using System.Threading.Tasks;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IApiMethodDefinitionRepository : IBaseRepository<ApiMethodDefinitionDto>
    {
        Task<RepoResponse<ApiMethodDefinitionDto>> GetByPkAsync(string key);
        Task<RepoResponse<List<GetApiMethodDefinitionsWithModuleNameResponseDto>>> GetApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName);
        Task<RepoResponse<List<GetApiMethodDefinitionsWithModelNameResponseDto>>> GetApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName);
        Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName);
        Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName);
        Task<RepoResponse<List<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>>> GetApiMethodAccessGrantsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey);
        Task<RepoResponse<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>> GetApiMethodAccessGrantsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string apiMethodAccessGrantsPermissionGroupName);
        Task<RepoResponse<List<GetKafkaEventsForApiMethodDefinitionsResponseDto>>> GetKafkaEventsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey);
        Task<RepoResponse<GetKafkaEventsForApiMethodDefinitionsResponseDto>> GetKafkaEventsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string kafkaEventsTopicName);
        Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName);
        Task<RepoResponse<int>> DeleteApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName);
    }
}