//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.TopicWorkflow;
using System.Threading.Tasks;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface ITopicWorkflowRepository : IBaseRepository<TopicWorkflowDto>
    {
        Task<RepoResponse<TopicWorkflowDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetWorkflowsResponseDto>>> GetWorkflowsAsync(string topicWorkflowKafkaEventsTopicName);
        Task<RepoResponse<List<GetWorkflows2ResponseDto>>> GetWorkflows2Async(string topicWorkflowKafkaEventsTopicName);
        Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod);
    }
}