//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.InterviewModule.Persistence.Contexts;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.Interviewer;
using QuickCode.Demomusti.InterviewModule.Application.Mappings;
using QuickCode.Demomusti.InterviewModule.Persistence.Sql;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Persistence.Repositories
{
    public partial class InterviewerRepository : BaseRepository, IInterviewerRepository
    {
        public async Task<RepoResponse<int>> ActivateAsync(int interviewerId, ActivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Interviewer", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interviewer.Command.Activate);
                var parameters = new
                {
                    PRM_INTERVIEWER_ID = interviewerId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int interviewerId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Interviewer", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interviewer.Command.Deactivate);
                var parameters = new
                {
                    PRM_INTERVIEWER_ID = interviewerId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}