//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.Demomusti.Portal.Models;
using QuickCode.Demomusti.Portal.Models.TrainingModule;
using QuickCode.Demomusti.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.Demomusti.Common.Nswag.Clients.IdentityModuleApi.Contracts;
using TrainingModuleContracts = QuickCode.Demomusti.Common.Nswag.Clients.TrainingModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.Demomusti.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.Demomusti.Portal.Controllers.TrainingModule
{
    [Permission("TrainingModuleTrainingFeedbacks")]
    [Area("TrainingModule")]
    [Route("TrainingModuleTrainingFeedbacks")]
    public partial class TrainingFeedbacksController : BaseController
    {
        private readonly TrainingModuleContracts.ITrainingFeedbacksClient pageClient;
        private readonly TrainingModuleContracts.IEmployeeTrainingsClient pageEmployeeTrainingClient;
        public TrainingFeedbacksController(TrainingModuleContracts.ITrainingFeedbacksClient pageClient, TrainingModuleContracts.IEmployeeTrainingsClient pageEmployeeTrainingClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pageEmployeeTrainingClient = pageEmployeeTrainingClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.TrainingFeedbacksInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.TrainingFeedbacksUpdateAsync(request.Id, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.TrainingFeedbacksDeleteAsync(request.Id);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(TrainingFeedbackData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(TrainingFeedbackData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(TrainingFeedbackData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<TrainingFeedbackData> PrepareModel()
        {
            var model = GetModel<TrainingFeedbackData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<TrainingFeedbackData> PrepareModel(TrainingFeedbackData model)
        {
            model.NumberOfRecord = await pageClient.TrainingFeedbacksCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.TrainingFeedbacksListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("EmployeeTrainings", () => pageEmployeeTrainingClient.EmployeeTrainingsListAsync()));
            return comboBoxList;
        }
    }
}