SELECT [ID], [CATEGORY_ID] 
FROM [TRAINING_CATEGORY_ASSIGNMENTS] 
WHERE [IsDeleted] = 0 
	AND [TRAINING_ID] = @PRM_TRAINING_CATEGORY_ASSIGNMENT_TRAINING_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 