SELECT [ID], [COMPANY_NAME], [JOB_TITLE], [START_DATE], [END_DATE] 
FROM [EXPERIENCES] 
WHERE [IsDeleted] = 0 
	AND [CANDIDATE_ID] = @PRM_EXPERIENCE_CANDIDATE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 