SELECT [ID], [CANDIDATE_ID], [INTERVIEW_DATE], [INTERVIEW_TYPE], [INTERVIEW_STATUS] 
FROM [INTERVIEWS] 
WHERE [IsDeleted] = 0 
	AND [INTERVIEWER_ID] = @PRM_INTERVIEW_INTERVIEWER_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 