SELECT [ID], [INTERVIEWER_ID], [INTERVIEW_DATE], [INTERVIEW_TYPE], [INTERVIEW_STATUS] 
FROM [INTERVIEWS] 
WHERE [IsDeleted] = 0 
	AND [CANDIDATE_ID] = @PRM_INTERVIEW_CANDIDATE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 