SELECT [ID], [CANDIDATE_ID], [INTERVIEWER_ID], [INTERVIEW_DATE] 
FROM [INTERVIEWS] 
WHERE [IsDeleted] = 0 
	AND [INTERVIEW_STATUS] = @PRM_INTERVIEW_INTERVIEW_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 