SELECT [ID], [FEEDBACK_TEXT], [RATING], [FEEDBACK_DATE] 
FROM [TRAINING_FEEDBACKS] 
WHERE [IsDeleted] = 0 
	AND [EMPLOYEE_TRAINING_ID] = @PRM_TRAINING_FEEDBACK_EMPLOYEE_TRAINING_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 