//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.InterviewFeedbackQuestion;
using System.Threading.Tasks;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Application.Interfaces.Repositories
{
    public partial interface IInterviewFeedbackQuestionRepository : IBaseRepository<InterviewFeedbackQuestionDto>
    {
        Task<RepoResponse<InterviewFeedbackQuestionDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync();
        Task<RepoResponse<List<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>>> GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsAsync(int interviewFeedbackQuestionsId);
        Task<RepoResponse<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>> GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsDetailsAsync(int interviewFeedbackQuestionsId, int interviewFeedbackAnswersId);
    }
}