SELECT [ID], [SOURCE_TYPE_ID] 
FROM [CANDIDATE_SOURCES] 
WHERE [IsDeleted] = 0 
	AND [CANDIDATE_ID] = @PRM_CANDIDATE_SOURCE_CANDIDATE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 