//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.TrainingModule.Persistence.Contexts;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.Training;
using QuickCode.Demomusti.TrainingModule.Application.Mappings;
using QuickCode.Demomusti.TrainingModule.Persistence.Sql;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Persistence.Repositories
{
    public partial class TrainingRepository : BaseRepository, ITrainingRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool trainingIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Training.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_TRAINING_IS_ACTIVE = trainingIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Training");
                }
            });
        }

        public async Task<RepoResponse<List<GetByTypeResponseDto>>> GetByTypeAsync(TrainingType trainingTrainingType, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByType", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByTypeResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Training.Query.GetByType);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_TRAINING_TRAINING_TYPE = trainingTrainingType,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByTypeResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Training");
                }
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(TrainingStatus trainingStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Training.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_TRAINING_STATUS = trainingStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Training");
                }
            });
        }

        public async Task<RepoResponse<List<GetEmployeeTrainingsForTrainingResponseDto>>> GetEmployeeTrainingsForTrainingAsync(int trainingId)
        {
            return await ExecuteWithExceptionHandling("GetEmployeeTrainingsForTraining", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetEmployeeTrainingsForTraining);
                var parameters = new
                {
                    trainingId = trainingId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetEmployeeTrainingsForTrainingResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Training");
            });
        }

        public async Task<RepoResponse<GetEmployeeTrainingsForTrainingResponseDto>> GetEmployeeTrainingsForTrainingDetailsAsync(int trainingId, int employeeTrainingsId)
        {
            return await ExecuteWithExceptionHandling("GetEmployeeTrainingsForTrainingDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetEmployeeTrainingsForTrainingDetails);
                var parameters = new
                {
                    trainingId = trainingId,
                    employeeTrainingsId = employeeTrainingsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetEmployeeTrainingsForTrainingResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Training");
            });
        }

        public async Task<RepoResponse<List<GetTrainingMaterialsForTrainingResponseDto>>> GetTrainingMaterialsForTrainingAsync(int trainingId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingMaterialsForTraining", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingMaterialsForTraining);
                var parameters = new
                {
                    trainingId = trainingId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTrainingMaterialsForTrainingResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Training");
            });
        }

        public async Task<RepoResponse<GetTrainingMaterialsForTrainingResponseDto>> GetTrainingMaterialsForTrainingDetailsAsync(int trainingId, int trainingMaterialsId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingMaterialsForTrainingDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingMaterialsForTrainingDetails);
                var parameters = new
                {
                    trainingId = trainingId,
                    trainingMaterialsId = trainingMaterialsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetTrainingMaterialsForTrainingResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Training");
            });
        }

        public async Task<RepoResponse<List<GetTrainingSessionsForTrainingResponseDto>>> GetTrainingSessionsForTrainingAsync(int trainingId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingSessionsForTraining", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingSessionsForTraining);
                var parameters = new
                {
                    trainingId = trainingId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTrainingSessionsForTrainingResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Training");
            });
        }

        public async Task<RepoResponse<GetTrainingSessionsForTrainingResponseDto>> GetTrainingSessionsForTrainingDetailsAsync(int trainingId, int trainingSessionsId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingSessionsForTrainingDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingSessionsForTrainingDetails);
                var parameters = new
                {
                    trainingId = trainingId,
                    trainingSessionsId = trainingSessionsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetTrainingSessionsForTrainingResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Training");
            });
        }

        public async Task<RepoResponse<List<GetTrainingCategoryAssignmentsForTrainingResponseDto>>> GetTrainingCategoryAssignmentsForTrainingAsync(int trainingId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingCategoryAssignmentsForTraining", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingCategoryAssignmentsForTraining);
                var parameters = new
                {
                    trainingId = trainingId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTrainingCategoryAssignmentsForTrainingResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Training");
            });
        }

        public async Task<RepoResponse<GetTrainingCategoryAssignmentsForTrainingResponseDto>> GetTrainingCategoryAssignmentsForTrainingDetailsAsync(int trainingId, int trainingCategoryAssignmentsId)
        {
            return await ExecuteWithExceptionHandling("GetTrainingCategoryAssignmentsForTrainingDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Query.GetTrainingCategoryAssignmentsForTrainingDetails);
                var parameters = new
                {
                    trainingId = trainingId,
                    trainingCategoryAssignmentsId = trainingCategoryAssignmentsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetTrainingCategoryAssignmentsForTrainingResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Training");
            });
        }
    }
}