//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.TrainingModule.Persistence.Contexts;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.Training;
using QuickCode.Demomusti.TrainingModule.Application.Mappings;
using QuickCode.Demomusti.TrainingModule.Persistence.Sql;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Persistence.Repositories
{
    public partial class TrainingRepository : BaseRepository, ITrainingRepository
    {
        public async Task<RepoResponse<int>> UpdateStatusAsync(int trainingId, UpdateStatusRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Training", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Training.Command.UpdateStatus);
                var parameters = new
                {
                    TRAINING_STATUS = updateRequest.TrainingStatus,
                    PRM_TRAINING_ID = trainingId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}