SELECT [ID], [NOTE], [CREATED_DATE] 
FROM [APPLICATION_NOTES] 
WHERE [IsDeleted] = 0 
	AND [CANDIDATE_ID] = @PRM_APPLICATION_NOTE_CANDIDATE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 