using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuickCode.Demomusti.IdentityModule.Domain.Enums;

public enum ModificationType{
	[Description("Generated by system")]
	System,
	[Description("Defined manually by user")]
	User,
	[Description("Explicitly disabled by user")]
	UserDisabled
}
