//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.AspNetUserRole;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Application.Mappings
{
    public static class AspNetUserRoleMappings
    {
        public static List<AspNetUserRoleDto> ToDto(this IEnumerable<AspNetUserRole> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserRoleDto ToDto(this AspNetUserRole model)
        {
            return new AspNetUserRoleDto
            {
                UserId = model.UserId,
                RoleId = model.RoleId
            };
        }

        public static AspNetUserRole ToEntity(this AspNetUserRoleDto model)
        {
            return new AspNetUserRole
            {
                UserId = model.UserId,
                RoleId = model.RoleId
            };
        }
    }
}