//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.AspNetUserLogin;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Application.Mappings
{
    public static class AspNetUserLoginMappings
    {
        public static List<AspNetUserLoginDto> ToDto(this IEnumerable<AspNetUserLogin> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserLoginDto ToDto(this AspNetUserLogin model)
        {
            return new AspNetUserLoginDto
            {
                LoginProvider = model.LoginProvider,
                ProviderKey = model.ProviderKey,
                ProviderDisplayName = model.ProviderDisplayName,
                UserId = model.UserId
            };
        }

        public static AspNetUserLogin ToEntity(this AspNetUserLoginDto model)
        {
            return new AspNetUserLogin
            {
                LoginProvider = model.LoginProvider,
                ProviderKey = model.ProviderKey,
                ProviderDisplayName = model.ProviderDisplayName,
                UserId = model.UserId
            };
        }
    }
}