//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.InterviewModule.Persistence.Contexts;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.Interview;
using QuickCode.Demomusti.InterviewModule.Application.Mappings;
using QuickCode.Demomusti.InterviewModule.Persistence.Sql;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Persistence.Repositories
{
    public partial class InterviewRepository : BaseRepository, IInterviewRepository
    {
        public async Task<RepoResponse<List<GetByCandidateResponseDto>>> GetByCandidateAsync(int interviewCandidateId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByCandidate", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCandidateResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetByCandidate);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_INTERVIEW_CANDIDATE_ID = interviewCandidateId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByCandidateResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Interview");
                }
            });
        }

        public async Task<RepoResponse<List<GetByInterviewerResponseDto>>> GetByInterviewerAsync(int interviewInterviewerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByInterviewer", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByInterviewerResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetByInterviewer);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_INTERVIEW_INTERVIEWER_ID = interviewInterviewerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByInterviewerResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Interview");
                }
            });
        }

        public async Task<RepoResponse<List<GetScheduledResponseDto>>> GetScheduledAsync(InterviewStatus interviewInterviewStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetScheduled", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetScheduledResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetScheduled);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_INTERVIEW_INTERVIEW_STATUS = interviewInterviewStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetScheduledResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Interview");
                }
            });
        }

        public async Task<RepoResponse<List<GetCompletedResponseDto>>> GetCompletedAsync(InterviewStatus interviewInterviewStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetCompleted", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCompletedResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetCompleted);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_INTERVIEW_INTERVIEW_STATUS = interviewInterviewStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetCompletedResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Interview");
                }
            });
        }

        public async Task<RepoResponse<List<GetInterviewFeedbackAnswersForInterviewsResponseDto>>> GetInterviewFeedbackAnswersForInterviewsAsync(int interviewsId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewFeedbackAnswersForInterviews", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewFeedbackAnswersForInterviews);
                var parameters = new
                {
                    interviewsId = interviewsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetInterviewFeedbackAnswersForInterviewsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Interview");
            });
        }

        public async Task<RepoResponse<GetInterviewFeedbackAnswersForInterviewsResponseDto>> GetInterviewFeedbackAnswersForInterviewsDetailsAsync(int interviewsId, int interviewFeedbackAnswersId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewFeedbackAnswersForInterviewsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewFeedbackAnswersForInterviewsDetails);
                var parameters = new
                {
                    interviewsId = interviewsId,
                    interviewFeedbackAnswersId = interviewFeedbackAnswersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetInterviewFeedbackAnswersForInterviewsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Interview");
            });
        }

        public async Task<RepoResponse<List<GetInterviewSchedulesForInterviewsResponseDto>>> GetInterviewSchedulesForInterviewsAsync(int interviewsId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewSchedulesForInterviews", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewSchedulesForInterviews);
                var parameters = new
                {
                    interviewsId = interviewsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetInterviewSchedulesForInterviewsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Interview");
            });
        }

        public async Task<RepoResponse<GetInterviewSchedulesForInterviewsResponseDto>> GetInterviewSchedulesForInterviewsDetailsAsync(int interviewsId, int interviewSchedulesId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewSchedulesForInterviewsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewSchedulesForInterviewsDetails);
                var parameters = new
                {
                    interviewsId = interviewsId,
                    interviewSchedulesId = interviewSchedulesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetInterviewSchedulesForInterviewsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Interview");
            });
        }

        public async Task<RepoResponse<List<GetInterviewNotesForInterviewsResponseDto>>> GetInterviewNotesForInterviewsAsync(int interviewsId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewNotesForInterviews", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewNotesForInterviews);
                var parameters = new
                {
                    interviewsId = interviewsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetInterviewNotesForInterviewsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Interview");
            });
        }

        public async Task<RepoResponse<GetInterviewNotesForInterviewsResponseDto>> GetInterviewNotesForInterviewsDetailsAsync(int interviewsId, int interviewNotesId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewNotesForInterviewsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Interview.Query.GetInterviewNotesForInterviewsDetails);
                var parameters = new
                {
                    interviewsId = interviewsId,
                    interviewNotesId = interviewNotesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetInterviewNotesForInterviewsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Interview");
            });
        }
    }
}