//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Application.Dtos.Interview
{
    public record GetInterviewNotesForInterviewsResponseDto
    {
        public int Id { get; init; }
        public int InterviewId { get; init; }
        public string NoteText { get; init; }
        public DateTime CreatedDate { get; init; }
    }
}