//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.EmployeeTraining;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Application.Mappings
{
    public static class EmployeeTrainingMappings
    {
        public static List<EmployeeTrainingDto> ToDto(this IEnumerable<EmployeeTraining> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static EmployeeTrainingDto ToDto(this EmployeeTraining model)
        {
            return new EmployeeTrainingDto
            {
                Id = model.Id,
                EmployeeId = model.EmployeeId,
                TrainingId = model.TrainingId,
                EnrollmentDate = model.EnrollmentDate,
                CompletionDate = model.CompletionDate,
                Grade = model.Grade
            };
        }

        public static EmployeeTraining ToEntity(this EmployeeTrainingDto model)
        {
            return new EmployeeTraining
            {
                Id = model.Id,
                EmployeeId = model.EmployeeId,
                TrainingId = model.TrainingId,
                EnrollmentDate = model.EnrollmentDate,
                CompletionDate = model.CompletionDate,
                Grade = model.Grade
            };
        }
    }
}