//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.Training;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Application.Mappings
{
    public static class TrainingMappings
    {
        public static List<TrainingDto> ToDto(this IEnumerable<Training> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TrainingDto ToDto(this Training model)
        {
            return new TrainingDto
            {
                Id = model.Id,
                CourseName = model.CourseName,
                Description = model.Description,
                TrainingType = model.TrainingType,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                Status = model.Status,
                CreatedDate = model.CreatedDate,
                IsActive = model.IsActive
            };
        }

        public static Training ToEntity(this TrainingDto model)
        {
            return new Training
            {
                Id = model.Id,
                CourseName = model.CourseName,
                Description = model.Description,
                TrainingType = model.TrainingType,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
                Status = model.Status,
                CreatedDate = model.CreatedDate,
                IsActive = model.IsActive
            };
        }
    }
}