//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.TrainingFeedback;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Application.Mappings
{
    public static class TrainingFeedbackMappings
    {
        public static List<TrainingFeedbackDto> ToDto(this IEnumerable<TrainingFeedback> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TrainingFeedbackDto ToDto(this TrainingFeedback model)
        {
            return new TrainingFeedbackDto
            {
                Id = model.Id,
                EmployeeTrainingId = model.EmployeeTrainingId,
                FeedbackText = model.FeedbackText,
                Rating = model.Rating,
                FeedbackDate = model.FeedbackDate
            };
        }

        public static TrainingFeedback ToEntity(this TrainingFeedbackDto model)
        {
            return new TrainingFeedback
            {
                Id = model.Id,
                EmployeeTrainingId = model.EmployeeTrainingId,
                FeedbackText = model.FeedbackText,
                Rating = model.Rating,
                FeedbackDate = model.FeedbackDate
            };
        }
    }
}