//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.TrainingModule.Application.Dtos.TrainingSession;
using QuickCode.Demomusti.TrainingModule.Domain.Entities;
using QuickCode.Demomusti.TrainingModule.Domain.Enums;

namespace QuickCode.Demomusti.TrainingModule.Application.Mappings
{
    public static class TrainingSessionMappings
    {
        public static List<TrainingSessionDto> ToDto(this IEnumerable<TrainingSession> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TrainingSessionDto ToDto(this TrainingSession model)
        {
            return new TrainingSessionDto
            {
                Id = model.Id,
                TrainingId = model.TrainingId,
                SessionName = model.SessionName,
                SessionDate = model.SessionDate,
                SessionLocation = model.SessionLocation
            };
        }

        public static TrainingSession ToEntity(this TrainingSessionDto model)
        {
            return new TrainingSession
            {
                Id = model.Id,
                TrainingId = model.TrainingId,
                SessionName = model.SessionName,
                SessionDate = model.SessionDate,
                SessionLocation = model.SessionLocation
            };
        }
    }
}