SELECT [ID], [SCHEDULED_TIME], [ROOM_NUMBER] 
FROM [INTERVIEW_SCHEDULES] 
WHERE [IsDeleted] = 0 
	AND [INTERVIEW_ID] = @PRM_INTERVIEW_SCHEDULE_INTERVIEW_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 