//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.SourceType;
using System.Threading.Tasks;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Application.Interfaces.Repositories
{
    public partial interface ISourceTypeRepository : IBaseRepository<SourceTypeDto>
    {
        Task<RepoResponse<SourceTypeDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync();
        Task<RepoResponse<List<GetCandidateSourcesForSourceTypesResponseDto>>> GetCandidateSourcesForSourceTypesAsync(int sourceTypesId);
        Task<RepoResponse<GetCandidateSourcesForSourceTypesResponseDto>> GetCandidateSourcesForSourceTypesDetailsAsync(int sourceTypesId, int candidateSourcesId);
    }
}