//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.InterviewFeedbackAnswer;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Application.Mappings
{
    public static class InterviewFeedbackAnswerMappings
    {
        public static List<InterviewFeedbackAnswerDto> ToDto(this IEnumerable<InterviewFeedbackAnswer> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static InterviewFeedbackAnswerDto ToDto(this InterviewFeedbackAnswer model)
        {
            return new InterviewFeedbackAnswerDto
            {
                Id = model.Id,
                InterviewId = model.InterviewId,
                QuestionId = model.QuestionId,
                AnswerText = model.AnswerText,
                AnswerRating = model.AnswerRating
            };
        }

        public static InterviewFeedbackAnswer ToEntity(this InterviewFeedbackAnswerDto model)
        {
            return new InterviewFeedbackAnswer
            {
                Id = model.Id,
                InterviewId = model.InterviewId,
                QuestionId = model.QuestionId,
                AnswerText = model.AnswerText,
                AnswerRating = model.AnswerRating
            };
        }
    }
}