//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.InterviewNote;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Application.Mappings
{
    public static class InterviewNoteMappings
    {
        public static List<InterviewNoteDto> ToDto(this IEnumerable<InterviewNote> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static InterviewNoteDto ToDto(this InterviewNote model)
        {
            return new InterviewNoteDto
            {
                Id = model.Id,
                InterviewId = model.InterviewId,
                NoteText = model.NoteText,
                CreatedDate = model.CreatedDate
            };
        }

        public static InterviewNote ToEntity(this InterviewNoteDto model)
        {
            return new InterviewNote
            {
                Id = model.Id,
                InterviewId = model.InterviewId,
                NoteText = model.NoteText,
                CreatedDate = model.CreatedDate
            };
        }
    }
}