SELECT [ID], [SESSION_NAME], [SESSION_DATE], [SESSION_LOCATION] 
FROM [TRAINING_SESSIONS] 
WHERE [IsDeleted] = 0 
	AND [TRAINING_ID] = @PRM_TRAINING_SESSION_TRAINING_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 