SELECT [ID], [DEGREE], [UNIVERSITY], [GRADUATION_DATE] 
FROM [QUALIFICATIONS] 
WHERE [IsDeleted] = 0 
	AND [CANDIDATE_ID] = @PRM_QUALIFICATION_CANDIDATE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 