//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.KafkaEvent;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Persistence.Sql;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class KafkaEventRepository : BaseRepository, IKafkaEventRepository
    {
        public async Task<RepoResponse<List<GetKafkaEventsResponseDto>>> GetKafkaEventsAsync()
        {
            return await ExecuteWithExceptionHandling("GetKafkaEvents", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetKafkaEvents);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetKafkaEventsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetActiveKafkaEventsResponseDto>>> GetActiveKafkaEventsAsync()
        {
            return await ExecuteWithExceptionHandling("GetActiveKafkaEvents", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetActiveKafkaEvents);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetActiveKafkaEventsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetTopicWorkflows);
                var parameters = new
                {
                    PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                    PRM_ApiMethodDefinitions_HttpMethod = apiMethodDefinitionsHttpMethod
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTopicWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsForKafkaEventsResponseDto>>> GetTopicWorkflowsForKafkaEventsAsync(string kafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflowsForKafkaEvents", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetTopicWorkflowsForKafkaEvents);
                var parameters = new
                {
                    kafkaEventsTopicName = kafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTopicWorkflowsForKafkaEventsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<GetTopicWorkflowsForKafkaEventsResponseDto>> GetTopicWorkflowsForKafkaEventsDetailsAsync(string kafkaEventsTopicName, int topicWorkflowsId)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflowsForKafkaEventsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetTopicWorkflowsForKafkaEventsDetails);
                var parameters = new
                {
                    kafkaEventsTopicName = kafkaEventsTopicName,
                    topicWorkflowsId = topicWorkflowsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetTopicWorkflowsForKafkaEventsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in KafkaEvent");
            });
        }
    }
}