//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.InterviewModule.Domain.Entities;
using QuickCode.Demomusti.InterviewModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.InterviewModule.Persistence.Contexts;
using QuickCode.Demomusti.InterviewModule.Application.Dtos.InterviewFeedbackQuestion;
using QuickCode.Demomusti.InterviewModule.Application.Mappings;
using QuickCode.Demomusti.InterviewModule.Persistence.Sql;
using QuickCode.Demomusti.InterviewModule.Domain.Enums;

namespace QuickCode.Demomusti.InterviewModule.Persistence.Repositories
{
    public partial class InterviewFeedbackQuestionRepository : BaseRepository, IInterviewFeedbackQuestionRepository
    {
        public async Task<RepoResponse<List<GetAllResponseDto>>> GetAllAsync()
        {
            return await ExecuteWithExceptionHandling("GetAll", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.InterviewFeedbackQuestion.Query.GetAll);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAllResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in InterviewFeedbackQuestion");
            });
        }

        public async Task<RepoResponse<List<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>>> GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsAsync(int interviewFeedbackQuestionsId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewFeedbackAnswersForInterviewFeedbackQuestions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.InterviewFeedbackQuestion.Query.GetInterviewFeedbackAnswersForInterviewFeedbackQuestions);
                var parameters = new
                {
                    interviewFeedbackQuestionsId = interviewFeedbackQuestionsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in InterviewFeedbackQuestion");
            });
        }

        public async Task<RepoResponse<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>> GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsDetailsAsync(int interviewFeedbackQuestionsId, int interviewFeedbackAnswersId)
        {
            return await ExecuteWithExceptionHandling("GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.InterviewFeedbackQuestion.Query.GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsDetails);
                var parameters = new
                {
                    interviewFeedbackQuestionsId = interviewFeedbackQuestionsId,
                    interviewFeedbackAnswersId = interviewFeedbackAnswersId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetInterviewFeedbackAnswersForInterviewFeedbackQuestionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in InterviewFeedbackQuestion");
            });
        }
    }
}