SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL], [PHONE_NUMBER] 
FROM [CANDIDATES] 
WHERE [IsDeleted] = 0 
	AND [IS_ACTIVE] = @PRM_CANDIDATE_IS_ACTIVE 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 