SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL] 
FROM [CANDIDATES] 
WHERE [IsDeleted] = 0 
	AND [APPLICATION_STATUS] = @PRM_CANDIDATE_APPLICATION_STATUS 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 