SELECT [ID], [FIRST_NAME], [LAST_NAME], [APPLICATION_DATE] 
FROM [CANDIDATES] 
WHERE [IsDeleted] = 0 
	AND [APPLICATION_DATE] > DATEADD(DAY, -30,
	GETDATE()) 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 