SELECT [ID], [FIRST_NAME], [LAST_NAME], [EMAIL] 
FROM [CANDIDATES] 
WHERE [IsDeleted] = 0 
	AND [FIRST_NAME] LIKE '%' + @PRM_CANDIDATE_FIRST_NAME + '%' 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 