SELECT [ID], [MATERIAL_NAME], [MATERIAL_URL] 
FROM [TRAINING_MATERIALS] 
WHERE [IsDeleted] = 0 
	AND [TRAINING_ID] = @PRM_TRAINING_MATERIAL_TRAINING_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 