//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.CandidateTrackingModule.Persistence.Contexts;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.Experience;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Mappings;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Persistence.Repositories
{
    public partial class ExperienceRepository : BaseRepository, IExperienceRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public ExperienceRepository(ILogger<ExperienceRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "Experience")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<ExperienceDto>> InsertAsync(ExperienceDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.Experience.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<ExperienceDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ExperienceDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.Experience>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ExperienceDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.Experience.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<ExperienceDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from experience in _readContext.Experience
                    where experience.Id.Equals(id)
                    select experience;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<ExperienceDto>
                {
                    Code = 404,
                    Message = "Not found in Experience"
                }

                : new RepoResponse<ExperienceDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<ExperienceDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ExperienceDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.Experience.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<ExperienceDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.Experience.CountAsync(), "Success");
            });
        }
    }
}