//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.AspNetRole;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Persistence.Sql;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class AspNetRoleRepository : BaseRepository, IAspNetRoleRepository
    {
        public async Task<RepoResponse<List<GetAspNetUserRolesForAspNetRolesResponseDto>>> GetAspNetUserRolesForAspNetRolesAsync(string aspNetRolesId)
        {
            return await ExecuteWithExceptionHandling("GetAspNetUserRolesForAspNetRoles", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Query.GetAspNetUserRolesForAspNetRoles);
                var parameters = new
                {
                    aspNetRolesId = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAspNetUserRolesForAspNetRolesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetRole");
            });
        }

        public async Task<RepoResponse<GetAspNetUserRolesForAspNetRolesResponseDto>> GetAspNetUserRolesForAspNetRolesDetailsAsync(string aspNetRolesId, string aspNetUserRolesUserId)
        {
            return await ExecuteWithExceptionHandling("GetAspNetUserRolesForAspNetRolesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Query.GetAspNetUserRolesForAspNetRolesDetails);
                var parameters = new
                {
                    aspNetRolesId = aspNetRolesId,
                    aspNetUserRolesUserId = aspNetUserRolesUserId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAspNetUserRolesForAspNetRolesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AspNetRole");
            });
        }

        public async Task<RepoResponse<List<GetAspNetRoleClaimsForAspNetRolesResponseDto>>> GetAspNetRoleClaimsForAspNetRolesAsync(string aspNetRolesId)
        {
            return await ExecuteWithExceptionHandling("GetAspNetRoleClaimsForAspNetRoles", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Query.GetAspNetRoleClaimsForAspNetRoles);
                var parameters = new
                {
                    aspNetRolesId = aspNetRolesId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetAspNetRoleClaimsForAspNetRolesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in AspNetRole");
            });
        }

        public async Task<RepoResponse<GetAspNetRoleClaimsForAspNetRolesResponseDto>> GetAspNetRoleClaimsForAspNetRolesDetailsAsync(string aspNetRolesId, int aspNetRoleClaimsId)
        {
            return await ExecuteWithExceptionHandling("GetAspNetRoleClaimsForAspNetRolesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AspNetRole.Query.GetAspNetRoleClaimsForAspNetRolesDetails);
                var parameters = new
                {
                    aspNetRolesId = aspNetRolesId,
                    aspNetRoleClaimsId = aspNetRoleClaimsId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAspNetRoleClaimsForAspNetRolesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AspNetRole");
            });
        }
    }
}