SELECT [ID], [NOTE_TEXT], [CREATED_DATE] 
FROM [INTERVIEW_NOTES] 
WHERE [IsDeleted] = 0 
	AND [INTERVIEW_ID] = @PRM_INTERVIEW_NOTE_INTERVIEW_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 