//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.ApiMethodDefinition;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Persistence.Sql;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodDefinitionRepository : BaseRepository, IApiMethodDefinitionRepository
    {
        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModuleNameResponseDto>>> GetApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModuleNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsWithModelNameResponseDto>>> GetApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsWithModelNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModuleNameAsync(string apiMethodDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModuleName = apiMethodDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsApiMethodDefinitionsWithModelNameAsync(string apiMethodDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("ExistsApiMethodDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.ExistsApiMethodDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_ApiMethodDefinition_ModelName = apiMethodDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>>> GetApiMethodAccessGrantsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForApiMethodDefinitions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodAccessGrantsForApiMethodDefinitions);
                var parameters = new
                {
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>> GetApiMethodAccessGrantsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string apiMethodAccessGrantsPermissionGroupName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodAccessGrantsForApiMethodDefinitionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetApiMethodAccessGrantsForApiMethodDefinitionsDetails);
                var parameters = new
                {
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey,
                    apiMethodAccessGrantsPermissionGroupName = apiMethodAccessGrantsPermissionGroupName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodAccessGrantsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<List<GetKafkaEventsForApiMethodDefinitionsResponseDto>>> GetKafkaEventsForApiMethodDefinitionsAsync(string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetKafkaEventsForApiMethodDefinitions", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetKafkaEventsForApiMethodDefinitions);
                var parameters = new
                {
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetKafkaEventsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ApiMethodDefinition");
            });
        }

        public async Task<RepoResponse<GetKafkaEventsForApiMethodDefinitionsResponseDto>> GetKafkaEventsForApiMethodDefinitionsDetailsAsync(string apiMethodDefinitionsKey, string kafkaEventsTopicName)
        {
            return await ExecuteWithExceptionHandling("GetKafkaEventsForApiMethodDefinitionsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ApiMethodDefinition.Query.GetKafkaEventsForApiMethodDefinitionsDetails);
                var parameters = new
                {
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey,
                    kafkaEventsTopicName = kafkaEventsTopicName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetKafkaEventsForApiMethodDefinitionsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ApiMethodDefinition");
            });
        }
    }
}