//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.Model;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Persistence.Sql;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class ModelRepository : BaseRepository, IModelRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string modelModuleName)
        {
            return await ExecuteWithExceptionHandling("ModuleNameIsExists", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Model_ModuleName = modelModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Model");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsForModelsResponseDto>>> GetApiMethodDefinitionsForModelsAsync(string modelsName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModels", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.GetApiMethodDefinitionsForModels);
                var parameters = new
                {
                    modelsName = modelsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsForModelsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Model");
            });
        }

        public async Task<RepoResponse<GetApiMethodDefinitionsForModelsResponseDto>> GetApiMethodDefinitionsForModelsDetailsAsync(string modelsName, string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModelsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.GetApiMethodDefinitionsForModelsDetails);
                var parameters = new
                {
                    modelsName = modelsName,
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodDefinitionsForModelsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Model");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageDefinitionsForModelsResponseDto>>> GetPortalPageDefinitionsForModelsAsync(string modelsName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModels", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.GetPortalPageDefinitionsForModels);
                var parameters = new
                {
                    modelsName = modelsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsForModelsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Model");
            });
        }

        public async Task<RepoResponse<GetPortalPageDefinitionsForModelsResponseDto>> GetPortalPageDefinitionsForModelsDetailsAsync(string modelsName, string portalPageDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModelsDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Model.Query.GetPortalPageDefinitionsForModelsDetails);
                var parameters = new
                {
                    modelsName = modelsName,
                    portalPageDefinitionsKey = portalPageDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPortalPageDefinitionsForModelsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Model");
            });
        }
    }
}