SELECT [ID], [TRAINING_ID], [ENROLLMENT_DATE], [COMPLETION_DATE], [GRADE] 
FROM [EMPLOYEE_TRAININGS] 
WHERE [IsDeleted] = 0 
	AND [EMPLOYEE_ID] = @PRM_EMPLOYEE_TRAINING_EMPLOYEE_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 