SELECT [ID], [EMPLOYEE_ID], [ENROLLMENT_DATE], [COMPLETION_DATE], [GRADE] 
FROM [EMPLOYEE_TRAININGS] 
WHERE [IsDeleted] = 0 
	AND [TRAINING_ID] = @PRM_EMPLOYEE_TRAINING_TRAINING_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 