SELECT [ID], [QUESTION_ID], [ANSWER_TEXT], [ANSWER_RATING] 
FROM [INTERVIEW_FEEDBACK_ANSWERS] 
WHERE [IsDeleted] = 0 
	AND [INTERVIEW_ID] = @PRM_INTERVIEW_FEEDBACK_ANSWER_INTERVIEW_ID 
ORDER BY [ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 