//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.ApplicationNote;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Application.Mappings
{
    public static class ApplicationNoteMappings
    {
        public static List<ApplicationNoteDto> ToDto(this IEnumerable<ApplicationNote> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ApplicationNoteDto ToDto(this ApplicationNote model)
        {
            return new ApplicationNoteDto
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                Note = model.Note,
                CreatedDate = model.CreatedDate
            };
        }

        public static ApplicationNote ToEntity(this ApplicationNoteDto model)
        {
            return new ApplicationNote
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                Note = model.Note,
                CreatedDate = model.CreatedDate
            };
        }
    }
}