//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.CandidateSource;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Application.Mappings
{
    public static class CandidateSourceMappings
    {
        public static List<CandidateSourceDto> ToDto(this IEnumerable<CandidateSource> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CandidateSourceDto ToDto(this CandidateSource model)
        {
            return new CandidateSourceDto
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                SourceTypeId = model.SourceTypeId
            };
        }

        public static CandidateSource ToEntity(this CandidateSourceDto model)
        {
            return new CandidateSource
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                SourceTypeId = model.SourceTypeId
            };
        }
    }
}