//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.Demomusti.CandidateTrackingModule.Application.Dtos.Qualification;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Entities;
using QuickCode.Demomusti.CandidateTrackingModule.Domain.Enums;

namespace QuickCode.Demomusti.CandidateTrackingModule.Application.Mappings
{
    public static class QualificationMappings
    {
        public static List<QualificationDto> ToDto(this IEnumerable<Qualification> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static QualificationDto ToDto(this Qualification model)
        {
            return new QualificationDto
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                Degree = model.Degree,
                University = model.University,
                GraduationDate = model.GraduationDate
            };
        }

        public static Qualification ToEntity(this QualificationDto model)
        {
            return new Qualification
            {
                Id = model.Id,
                CandidateId = model.CandidateId,
                Degree = model.Degree,
                University = model.University,
                GraduationDate = model.GraduationDate
            };
        }
    }
}