//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.ApiMethodAccessGrant;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class ApiMethodAccessGrantRepository : BaseRepository, IApiMethodAccessGrantRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public ApiMethodAccessGrantRepository(ILogger<ApiMethodAccessGrantRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "ApiMethodAccessGrant")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<ApiMethodAccessGrantDto>> InsertAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.ApiMethodAccessGrant.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<ApiMethodAccessGrantDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.ApiMethodAccessGrant>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(ApiMethodAccessGrantDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.ApiMethodAccessGrant.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<ApiMethodAccessGrantDto>> GetByPkAsync(string permissionGroupName, string apiMethodDefinitionKey)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from api_method_access_grant in _readContext.ApiMethodAccessGrant
                    where api_method_access_grant.PermissionGroupName.Equals(permissionGroupName) && api_method_access_grant.ApiMethodDefinitionKey.Equals(apiMethodDefinitionKey)
                    select api_method_access_grant;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<ApiMethodAccessGrantDto>
                {
                    Code = 404,
                    Message = "Not found in ApiMethodAccessGrant"
                }

                : new RepoResponse<ApiMethodAccessGrantDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<ApiMethodAccessGrantDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<ApiMethodAccessGrantDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.ApiMethodAccessGrant.OrderBy(o => o.PermissionGroupName).ThenBy(o => o.ApiMethodDefinitionKey).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<ApiMethodAccessGrantDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.ApiMethodAccessGrant.CountAsync(), "Success");
            });
        }
    }
}