//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.Demomusti.Common.Models;
using QuickCode.Demomusti.IdentityModule.Domain.Entities;
using QuickCode.Demomusti.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.Demomusti.Common;
using QuickCode.Demomusti.Common.Extensions;
using QuickCode.Demomusti.Common.Helpers;
using QuickCode.Demomusti.IdentityModule.Persistence.Contexts;
using QuickCode.Demomusti.IdentityModule.Application.Dtos.Module;
using QuickCode.Demomusti.IdentityModule.Application.Mappings;
using QuickCode.Demomusti.IdentityModule.Persistence.Sql;
using QuickCode.Demomusti.IdentityModule.Domain.Enums;

namespace QuickCode.Demomusti.IdentityModule.Persistence.Repositories
{
    public partial class ModuleRepository : BaseRepository, IModuleRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string moduleName)
        {
            return await ExecuteWithExceptionHandling("ModuleNameIsExists", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Module_Name = moduleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetModelsForModulesResponseDto>>> GetModelsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetModelsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetModelsForModules);
                var parameters = new
                {
                    modulesName = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetModelsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetModelsForModulesResponseDto>> GetModelsForModulesDetailsAsync(string modulesName, string modelsName)
        {
            return await ExecuteWithExceptionHandling("GetModelsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetModelsForModulesDetails);
                var parameters = new
                {
                    modulesName = modulesName,
                    modelsName = modelsName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetModelsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetApiMethodDefinitionsForModulesResponseDto>>> GetApiMethodDefinitionsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetApiMethodDefinitionsForModules);
                var parameters = new
                {
                    modulesName = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetApiMethodDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetApiMethodDefinitionsForModulesResponseDto>> GetApiMethodDefinitionsForModulesDetailsAsync(string modulesName, string apiMethodDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetApiMethodDefinitionsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetApiMethodDefinitionsForModulesDetails);
                var parameters = new
                {
                    modulesName = modulesName,
                    apiMethodDefinitionsKey = apiMethodDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetApiMethodDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageDefinitionsForModulesResponseDto>>> GetPortalPageDefinitionsForModulesAsync(string modulesName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModules", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetPortalPageDefinitionsForModules);
                var parameters = new
                {
                    modulesName = modulesName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in Module");
            });
        }

        public async Task<RepoResponse<GetPortalPageDefinitionsForModulesResponseDto>> GetPortalPageDefinitionsForModulesDetailsAsync(string modulesName, string portalPageDefinitionsKey)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsForModulesDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.GetPortalPageDefinitionsForModulesDetails);
                var parameters = new
                {
                    modulesName = modulesName,
                    portalPageDefinitionsKey = portalPageDefinitionsKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetPortalPageDefinitionsForModulesResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Module");
            });
        }
    }
}